# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateRatio',
            fields=[
                ('rate_ratio_date', models.DateField(primary_key=True, serialize=False)),
                ('rate_ratio', models.FloatField()),
            ],
            options={
                'db_table': 'exchange_rate_ratios',
                'managed': False,
            },
        ),
    ]
